<?php
$this->title = "Users";
$this->headTitle($this->title);
?>

<table>
<tr>
<th>Name</th>
<th>Email</th>
<th>&nbsp;</th>
</tr>
<?php foreach($this->users as $user) : ?>
<tr>
<td><?php echo $this->escape($user->name);?></td>
<td><?php echo $this->escape($user->email);?></td>
<td>
<a href="<?php echo $this->url(array('controller'=>'index',
'action'=>'edit', 'id'=>$user->id));?>">Edit</a>
<a href="<?php echo $this->url(array('controller'=>'index',
'action'=>'delete', 'id'=>$user->id));?>">Delete</a>
</td>
</tr>
<?php endforeach; ?>
</table>
<p><a href="<?php echo $this->url(array('controller'=>'index',
'action'=>'add'));?>">Add new user</a></p>	